import type { TokenData } from "./types"

export const tokenData: TokenData[] = [
  {
    id: "1",
    name: "SOL/USDC",
    symbol: "SOL/USDC",
    tvl: "88.4M",
    volume24h: "22.61M",
    fees24h: "115.5K",
    feeRatio: "3.2%",
    yourBalance: "-",
  },
  {
    id: "2",
    name: "SOL/AVAX",
    symbol: "SOL/AVAX",
    tvl: "88.4M",
    volume24h: "22.61M",
    fees24h: "115.5K",
    feeRatio: "3.2%",
    yourBalance: "-",
  },
  {
    id: "3",
    name: "SOL/USDT",
    symbol: "SOL/USDT",
    tvl: "88.4M",
    volume24h: "22.61M",
    fees24h: "115.5K",
    feeRatio: "3.2%",
    yourBalance: "-",
  },
  {
    id: "4",
    name: "SOL/USDC",
    symbol: "SOL/USDC",
    tvl: "88.4M",
    volume24h: "22.61M",
    fees24h: "115.5K",
    feeRatio: "3.2%",
    yourBalance: "-",
  },
  {
    id: "5",
    name: "SOL/BERA",
    symbol: "SOL/BERA",
    tvl: "88.4M",
    volume24h: "22.61M",
    fees24h: "115.5K",
    feeRatio: "3.2%",
    yourBalance: "-",
  },
  {
    id: "6",
    name: "SOL/USDC",
    symbol: "SOL/USDC",
    tvl: "88.4M",
    volume24h: "22.61M",
    fees24h: "115.5K",
    feeRatio: "3.2%",
    yourBalance: "-",
  },
]
